version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - chat_network

  backend:
    build:
      context: ./backend
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 64M
    ports:
      - "4000-4002:4000"
    networks:
      - chat_network
    volumes:
      - sqlite_data:/app/sqlite_data

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat_network

volumes:
  sqlite_data: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend/sqlite_data'

networks:
  chat_network:
    driver: bridge